# Generated by Django 5.2.1 on 2025-05-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_tutor_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='pswd',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='pswd',
            field=models.CharField(max_length=20),
        ),
    ]
